services:
  # Backend API Service
  - type: web
    name: copytrade-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: web
          name: copytrade-frontend
          property: url
      - key: ALLOWED_ORIGINS
        fromService:
          type: web
          name: copytrade-frontend
          property: url
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/trading.db
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_REQUEST_LOGGING
        value: true
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100

  # Frontend Static Site
  - type: web
    name: copytrade-frontend
    env: static
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: copytrade-backend
          property: url
          envVarKey: VITE_API_URL
      - key: VITE_APP_NAME
        value: CopyTrade Pro
      - key: VITE_APP_VERSION
        value: 1.0.0
      - key: VITE_NODE_ENV
        value: production
      - key: VITE_ENABLE_DEBUG
        value: false
      - key: VITE_ENABLE_ANALYTICS
        value: true

# Database (using disk storage for SQLite)
databases: []

# Additional configuration
buildFilter:
  paths:
    - backend/**
    - frontend/**
  ignoredPaths:
    - "*.md"
    - ".git/**"
    - "node_modules/**"
