services:
  # Full-Stack Application (Backend serving Frontend)
  #
  # ✅ WORKING MANUAL DEPLOYMENT CONFIGURATION FOR RENDER.COM:
  #
  # Build Command (TESTED & WORKING):
  # echo "Installing root dependencies..." && npm install --include=dev && echo "Building backend..." && cd backend && npm run build && echo "Building frontend..." && cd ../frontend && npm run build && echo "Copying frontend to backend..." && cd ../backend && mkdir -p public && cp -r ../frontend/dist/* public/ && echo "Build complete!"
  #
  # Start Command:
  # cd backend && npm start
  #
  # Environment Variables (copy to Render.com dashboard):
  # NODE_ENV=production
  # PORT=10000
  # JWT_SECRET=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6
  # ENCRYPTION_KEY=9f8e7d6c5b4a39281746352819047362518394756281947362851
  # FRONTEND_URL=https://copytradepro.onrender.com
  # ALLOWED_ORIGINS=https://copytradepro.onrender.com
  # DATABASE_PATH=/opt/render/project/src/backend/data/trading.db
  # LOG_LEVEL=info
  # ENABLE_REQUEST_LOGGING=true
  # RATE_LIMIT_WINDOW_MS=900000
  # RATE_LIMIT_MAX_REQUESTS=100
  # VITE_API_URL=https://copytradepro.onrender.com/api
  # VITE_APP_NAME=CopyTrade Pro
  # VITE_APP_VERSION=1.0.0
  # VITE_NODE_ENV=production
  # VITE_ENABLE_DEBUG=false
  # VITE_ENABLE_ANALYTICS=true
  #
  - type: web
    name: copytrade-pro
    runtime: node
    plan: starter
    buildCommand: |
      echo "🚀 Building CopyTrade Pro..."

      # Install root dependencies to set up workspace
      npm install

      # Build backend
      cd backend
      npm run build

      # Build frontend
      cd ../frontend
      npm run build

      # Copy frontend to backend public
      cd ../backend
      mkdir -p public
      cp -r ../frontend/dist/* public/

      echo "✅ Build completed!"
    startCommand: cd backend && node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://copytrade-pro.onrender.com
      - key: ALLOWED_ORIGINS
        value: https://copytrade-pro.onrender.com
      - key: DATABASE_PATH
        value: /opt/render/project/src/backend/data/trading.db
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_REQUEST_LOGGING
        value: "true"
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: VITE_API_URL
        value: https://copytrade-pro.onrender.com/api
      - key: VITE_APP_NAME
        value: CopyTrade Pro
      - key: VITE_APP_VERSION
        value: 1.0.0
      - key: VITE_NODE_ENV
        value: production
      - key: VITE_ENABLE_DEBUG
        value: "false"
      - key: VITE_ENABLE_ANALYTICS
        value: "true"

# Database (using disk storage for SQLite)
databases: []
