services:
  # Full-Stack Application (Backend serving Frontend)
  - type: web
    name: copytrade-pro
    runtime: node
    plan: starter
    buildCommand: |
      echo "🚀 Building CopyTrade Pro..."

      # Install and build backend
      cd backend
      npm install --only=production
      npm install typescript @types/node --save-dev
      npx tsc

      # Install and build frontend
      cd ../frontend
      npm install
      npm run build

      # Copy frontend to backend public
      cd ../backend
      mkdir -p public
      cp -r ../frontend/dist/* public/

      echo "✅ Build completed!"
    startCommand: cd backend && node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://copytrade-pro.onrender.com
      - key: ALLOWED_ORIGINS
        value: https://copytrade-pro.onrender.com
      - key: DATABASE_PATH
        value: /opt/render/project/src/backend/data/trading.db
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_REQUEST_LOGGING
        value: "true"
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: VITE_API_URL
        value: https://copytrade-pro.onrender.com/api
      - key: VITE_APP_NAME
        value: CopyTrade Pro
      - key: VITE_APP_VERSION
        value: 1.0.0
      - key: VITE_NODE_ENV
        value: production
      - key: VITE_ENABLE_DEBUG
        value: "false"
      - key: VITE_ENABLE_ANALYTICS
        value: "true"

# Database (using disk storage for SQLite)
databases: []
